### ISSUE TITLE
Android without QT bluetooth : stuck on foreach

### ISSUE THREAD

**Issue by jribal** [subsurface/libdc#17]
Hello,

I'm trying to make libsubsurface work with an OSTC Sport + without Qt Bluetooth, using an Android bluetooth system instead.

I managed to set the device to "download mode" but I seem stuck inside the `foreach()` function.

I have taken example from [qtserialbluetooth.cpp](https://github.com/Subsurface-divelog/subsurface/blob/v4.8.5/core/qtserialbluetooth.cpp) to setup the connection and callbacks.

My assumptions:
1. My device goes to "download mode" with `hw_ostc3_read` from [hw_ostc3.c line 285](https://github.com/Subsurface-divelog/libdc/blob/v4.8.5/src/hw_ostc3.c).  
2. `hw_ostc3_read` from [hw_ostc3.c line 293](https://github.com/Subsurface-divelog/libdc/blob/v4.8.5/src/hw_ostc3.c) should create a call to my "read" event from`dc_custom_cbs_t`.
3. From the read event I should call my bluetooth socket and fill the `void *data` with whatever was obtain from the device.
4. Then I should receive something inside my `dc_dive_callback_t` and start to extract dive information.

I also regularly receive data inside my "write" callback, something that looks like a keep alive for the bluetooth connection.

Are one of my assumptions wrong ?

Thank you for any future reply.

**Comment by dirkhh** [comment]
I don't think anyone here has ever tried anything like that.
We quite specifically are using Qt Bluetooth so we DON'T have to deal with the local stacks :-)

**Comment by glance-** [comment]
Nothing in your assumptions sounds wrong, but I might be missing something.

You can also look at https://github.com/Subsurface-divelog/subsurface/blob/v4.8.5/core/serial_ftdi.c as a example, of how a custom communication can be built.

My guess is that your communication layer fails in foreach because thats the first place where there are more than single byte communication going on, which might cause something to go wrong.

If you share your code it will be easier to spot the issue.

**Comment by jribal** [comment]
Thank you for your quick answers.

@dirkhh It makes sense if you don't bother with including the complete QT stack, it seems to work well for the subsurface project.

Here are my code and some logs.
[libsubsurface c-jni](https://gist.github.com/jribal/140ccbde7c54f6a434fa6b52cacace2f#file-gistfile1-txt)
[libsubsurface java-jni](https://gist.github.com/jribal/e542387a4e5ba799a2c2c9ca374f3701#file-gistfile1-txt)
[android logs](https://gist.github.com/jribal/d7a8aca2aa6160b771d9c0a276d677d4#file-gistfile1-txt)

@glance- In my logs you can see I only have one byte sent everytime, I checked it on Java and C sides.
I looked  at serial_ftdi.c and could not spot a big difference with qtserialbluetooth.c.

**Comment by jeanmatthieud** [comment]
Hi @jribal ,
Did you managed to read the data on Android with BLE without Qt ?
Do you have a repository ?

**Comment by jribal** [comment]
Hi @jeanmatthieud,

Sorry for the late response.
No I could not find a way to move forward.

I would be interested to know if you could find a solution.

No repository, It was for a client.
