### ISSUE TITLE
OSTC4 download dives fails with "Error parsing the header"

### ISSUE THREAD

**Issue by antiker1** [subsurface/libdc#9]
Hi.

From https://github.com/Subsurface-divelog/subsurface/issues/590

Trying to download the profiles from some trimix dives gives: "`Error parsing the header`" in the UI and
```
subsurface:~$ subsurface
[3.109370] ERROR: Invalid gas mix. [in hw_ostc_parser.c:843 (hw_ostc_parser_samples_foreach)]
```

Maybe it's because of this
https://user-images.githubusercontent.com/31750016/30662067-238ffc1e-9e46-11e7-8195-9307a779a135.jpg
Not sure how this happened... something with the gas change didn't work as it should (I was anyway diving after RT), and the ppO2 seems screwed up.

Any idea for a quick fix, as this blocks downloading all further new dives and I cannot write my logs now ;-)

Thanks!

**Comment by antiker1** [comment]
Has anyone ever had a look at this?
I'd really like to be able using my OSTC4 with subsurface/libdc, but right now this seems impossible. :-(

**Comment by dirkhh** [comment]
Current libdc works just fine with the OSTC4 (apologies for not responding earlier - I apparently didn't have notifications on for this repo for a short while... but hey, it's only been 2.5 years, right?)
